version: '3.8'

services:
  web:
    build: .

    image: django_web
    # '/start' is the shell script used to run the service
    command: python manage.py runserver 0.0.0.0:8000 #gunicorn arenda_site.wsgi:application --bind 0.0.0.0:8000
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/usr/src/
    ports:
      - '8000:8000'
    # env_file is used to manage the _p variables of our project
    env_file:
      - .docker_env/.dev-sample
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=arendadb
      - POSTGRES_USER=userdjango
      - POSTGRES_PASSWORD=userdjango

  redis:
    image: redis:6-alpine

  celery_worker:
    build: .

    image: celery_worker
    command: celery -A arenda_site worker -l INFO
    volumes:
      - .:/usr/src/
    env_file:
      - .docker_env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build: .

    image: celery_beat
    command: celery -A arenda_site beat -l INFO
    volumes:
      - .:/usr/src/
    env_file:
      - .docker_env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    build: .

    image: celery_flower
    command: celery -A arenda_site inspect ping
    volumes:
      - .:/usr/src/
    env_file:
      - .docker_env/.dev-sample
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: